# Generated by Django 2.2.5 on 2022-10-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(default='', max_length=25, null=True)),
                ('fname', models.CharField(default='', max_length=25, null=True)),
                ('midname', models.CharField(default='', max_length=25, null=True)),
                ('sname', models.CharField(default='', max_length=25, null=True)),
                ('mobno', models.BigIntegerField(default='', null=True)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
            ],
        ),
    ]
