# Generated by Django 2.2.5 on 2022-10-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmovie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='midname',
        ),
    ]
