# Generated by Django 2.2.5 on 2022-10-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmovie', '0002_auto_20221017_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_img', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
                ('movie_name', models.CharField(default='', max_length=50, null=True)),
                ('ticket_cost', models.IntegerField(default='', max_length=25, null=True)),
                ('movie_info', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
