# Generated by Django 2.2.5 on 2022-10-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmovie', '0003_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='lang',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/faces'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ticket_cost',
            field=models.IntegerField(),
        ),
    ]
