# Generated by Django 2.2.5 on 2022-10-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmovie', '0004_auto_20221024_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_img',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
