# Generated by Django 2.2.5 on 2022-10-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmovie', '0005_auto_20221025_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('occupant_first_name', models.CharField(max_length=255)),
                ('occupant_last_name', models.CharField(max_length=255)),
                ('occupant_email', models.CharField(max_length=255)),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='booked_seat',
            field=models.ManyToManyField(blank=True, null=True, to='bookmovie.Seat'),
        ),
    ]
